name: Web Vercel deploy
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: 'Test'
        required: false
        type: string
      vercel_org_id:
        description: 'The vercel organisation ID'
        required: true
        type: string
      vercel_project_id:
        description: 'The ID of the vercel project'
        required: true
        type: string
    secrets:
      npm_pat:
        description: The PAT for NPM registry access
        required: true
      vercel_auth_token:
        description: The vercel auth token for vercel access
        required: true

jobs:
  deploy_vercel:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: 'Preview deploy'
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PAT}}
        run: yarn install --production=false --frozen-lockfile
      - name: Deploy preview
        env:
          VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
          VERCEL_AUTH_TOKEN: ${{ secrets.vercel_auth_token }}
        run: npx vercel --prod --token="$VERCEL_AUTH_TOKEN"
