name: Test
on:
  workflow_call:
    secrets:
      npm_pat:
        description: The PAT for NPM registry access
        required: true

jobs:
    test:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        name: 'Test (node ${{ matrix.node-version }})'
        permissions:
          contents: read
        strategy:
          matrix:
            node-version: ['20.x']
            experimental: [false]
            include:
              - node-version: '22.x'
                experimental: true
        steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              persist-credentials: false
    
          - name: Setup node
            uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
            with:
              node-version: ${{ matrix.node-version }}
              registry-url: https://npm.pkg.github.com
              cache: yarn
    
          - name: Install dependencies
            run: yarn install --production=false --frozen-lockfile
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
    
          - name: Run unit tests
            run: yarn test